server:
  servlet:
    application-display-name: Echo

logging:
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO

hipchat:
  url: https://homonoia-studios.hipchat.com/v2/
  token: PR0WidETa8IWZHkrjmvuAvEzsePhcCDpTxIfGTYY
  user: 4193333
  callbacks:
    message: https://hs-echo-bot.herokuapp.com/hipchat/room-message
    notification: https://hs-echo-bot.herokuapp.com/hipchat/room-notification
    enter: https://hs-echo-bot.herokuapp.com/hipchat/room-enter
    exit: https://hs-echo-bot.herokuapp.com/hipchat/room-exit
  rooms:
    - Test
  plugins:
    core:
      friendly: true
      devops: true

info:
  version: "${project.version}"
  git:
    commit: "${project.ext.git.gitHash}"
    branch: "${project.ext.git.branchName}"

management:
  server:
    servlet:
      context-path: /manage


